#!/usr/bin/env bash
# Transfer data from client to server

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_PATH=$4

if (($# < 4)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    echo -n "" > ~/.ssh/config
    {
        echo "Host ${IP}"
        echo -e "\tUser ${USERNAME}"
        echo -e "\tIdentityFile ${SSH_PATH}"
        echo -e "\tPubKeyAuthentication yes"
        echo -e "\tStrictHostKeyChecking no"
    } >> ~/.ssh/config
    scp "${PATH_TO_FILE}" "${USERNAME}@${IP}:~/"
fi

