#!/usr/bin/env bash
# install an nginx web server as root

apt -y update
apt -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart

