#!/usr/bin/env bash
# configure new server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen 80 default_server;

	root /var/www/html;
	index index.html;

	error_page 404 /404.html;
	location = /404.html{
		internal;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > default_file
mv -f default_file /etc/nginx/sites-enabled/default
sed -i "s/http {/http {\n\tadd_header X-Served-By $(hostname);/" /etc/nginx/nginx.conf
service nginx restart
