#!/usr/bin/env bash
# Script backup and compress my databases
mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
archive_name="$day-$month-$year.tar.gz"
tar -czvf "$archive_name" backup.sql
