#!/usr/bin/env bash
# configure nginx server to listen to port 80
rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
