#!/usr/bin/env bash
# Print bad luck from, china for 4th, japan for 9th 17 for italy

i=1
while ((i <= 20)); do
	echo $i
	case $i in
		[1-9]|1[0-9]|2[0])
	if ((i==4)); then
		echo bad luck from China
	fi
	if ((i==9)); then
		echo bad luck from Japan
	fi
	if ((i==17)); then
		echo bad luck from Italy
	fi
	;;
	esac
	i=$((i + 1))
done
