#!/usr/bin/env bash
# run nginx as a user named nginx
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80;/8080;/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
